weights: yolov5n.pt
cfg: ''
data: C:\Users\Owner\Desktop\Perez_YOLO\yolov5\data\my_seeds.yaml
hyp: data/hyps/hyp.my_seed.yaml
epochs: 300
batch_size: 48
imgsz: 512
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: seeds
name: train_100n
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 10
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: seeds\train_100n
